package xjsnark.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0x39ce7332e3ec6ba5L) {
      return new InputBlock_Constraints();
    }
    if (id == 0x39ce7332e3fb13ebL) {
      return new OutputBlock_Constraints();
    }
    if (id == 0x6804d86d4b818deaL) {
      return new VerifiedWitnessBlock_Constraints();
    }
    if (id == 0x39ce7332e3fc3a64L) {
      return new WitnessBlock_Constraints();
    }
    if (id == 0x64cb8fa51401373bL) {
      return new ProgramDefinition_Constraints();
    }
    if (id == 0x701def9dcb9d54fcL) {
      return new StructDefinition_Constraints();
    }
    if (id == 0x1fa68170270e2608L) {
      return new InitMemory_Constraints();
    }
    if (id == 0x1fa6817027253167L) {
      return new MemoryAccessExpression_Constraints();
    }
    if (id == 0x1fa68170270e25b5L) {
      return new MemoryType_Constraints();
    }
    if (id == 0x1fa6817026d685c6L) {
      return new FieldInverseOp_Constraints();
    }
    if (id == 0x6804d86d4d430c5aL) {
      return new JFieldConversion_Constraints();
    }
    if (id == 0x7e3d44c18645a331L) {
      return new JUnsignedIntegerConversion_Constraints();
    }
    if (id == 0x56922dce2d44475dL) {
      return new BitsOp_Constraints();
    }
    if (id == 0x67fc252049b55c0dL) {
      return new ConversionBetweenTypes_Constraints();
    }
    if (id == 0x68d52c08c1986fe0L) {
      return new ExternalBlock_Constraints();
    }
    if (id == 0x6804d86d49d0931fL) {
      return new LabelBlock_Constraints();
    }
    if (id == 0x3d482b3147b16973L) {
      return new TestBlock_Constraints();
    }
    if (id == 0x68d52c08c1a5a40aL) {
      return new ValueOp_Constraints();
    }
    if (id == 0x26b0c1978f544467L) {
      return new JBooleanConversion_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
}
