package xjsnark.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.Arrays;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myMemoryType__BehaviorDescriptor = new MemoryType__BehaviorDescriptor();
  private final BHDescriptor myMemoryAccessExpression__BehaviorDescriptor = new MemoryAccessExpression__BehaviorDescriptor();
  private final BHDescriptor myJUnsignedIntegerType__BehaviorDescriptor = new JUnsignedIntegerType__BehaviorDescriptor();
  private final BHDescriptor myTestBlock__BehaviorDescriptor = new TestBlock__BehaviorDescriptor();
  private final BHDescriptor myJEqualsExpression__BehaviorDescriptor = new JEqualsExpression__BehaviorDescriptor();
  private final BHDescriptor myXjsnarkType__BehaviorDescriptor = new XjsnarkType__BehaviorDescriptor();
  private final BHDescriptor myJIntegerConstant__BehaviorDescriptor = new JIntegerConstant__BehaviorDescriptor();
  private final BHDescriptor myProgramDefinition__BehaviorDescriptor = new ProgramDefinition__BehaviorDescriptor();
  private final BHDescriptor myJAndExpression__BehaviorDescriptor = new JAndExpression__BehaviorDescriptor();
  private final BHDescriptor myJOrExpression__BehaviorDescriptor = new JOrExpression__BehaviorDescriptor();
  private final BHDescriptor myValueOp__BehaviorDescriptor = new ValueOp__BehaviorDescriptor();
  private final BHDescriptor myFieldDefTable__BehaviorDescriptor = new FieldDefTable__BehaviorDescriptor();
  private final BHDescriptor myFieldRecord__BehaviorDescriptor = new FieldRecord__BehaviorDescriptor();
  private final BHDescriptor myJNotEqualsExpression__BehaviorDescriptor = new JNotEqualsExpression__BehaviorDescriptor();
  private final BHDescriptor myJUnsignedBigIntegerLiteral__BehaviorDescriptor = new JUnsignedBigIntegerLiteral__BehaviorDescriptor();
  private final BHDescriptor myJUnsignedBigIntegerDecimalConstant__BehaviorDescriptor = new JUnsignedBigIntegerDecimalConstant__BehaviorDescriptor();
  private final BHDescriptor myJUnsignedBigIntegerHexConstant__BehaviorDescriptor = new JUnsignedBigIntegerHexConstant__BehaviorDescriptor();

  private final long[] myConceptBehaviorIds;

  public BehaviorAspectDescriptor() {
    myConceptBehaviorIds = new long[17];
    myConceptBehaviorIds[0] = 0x1fa68170270e25b5L;
    myConceptBehaviorIds[1] = 0x1fa6817027253167L;
    myConceptBehaviorIds[2] = 0x39ce7332e3fe6a0eL;
    myConceptBehaviorIds[3] = 0x3d482b3147b16973L;
    myConceptBehaviorIds[4] = 0x4bcdfddfee9be827L;
    myConceptBehaviorIds[5] = 0x61502e94ebf30481L;
    myConceptBehaviorIds[6] = 0x61502e94ec0554f2L;
    myConceptBehaviorIds[7] = 0x64cb8fa51401373bL;
    myConceptBehaviorIds[8] = 0x68d52c08c1829874L;
    myConceptBehaviorIds[9] = 0x68d52c08c1829875L;
    myConceptBehaviorIds[10] = 0x68d52c08c1a5a40aL;
    myConceptBehaviorIds[11] = 0x68d52c08c1c95ad1L;
    myConceptBehaviorIds[12] = 0x68d52c08c1c95ad2L;
    myConceptBehaviorIds[13] = 0x72b1138add75e682L;
    myConceptBehaviorIds[14] = 0x7cfe1585af18d4f2L;
    myConceptBehaviorIds[15] = 0x7cfe1585af18da2eL;
    myConceptBehaviorIds[16] = 0x7cfe1585af18e156L;
  }

  @Deprecated
  @Override
  public BehaviorDescriptor getDescriptor(String fqName) {
    return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
  }

  @Nullable
  @Override
  public BHDescriptor getDescriptor(@NotNull SConceptId conceptId) {
    int behaviorIndex = Arrays.binarySearch(myConceptBehaviorIds, conceptId.getIdValue());
    switch (behaviorIndex) {
      case 0:
        return myMemoryType__BehaviorDescriptor;
      case 1:
        return myMemoryAccessExpression__BehaviorDescriptor;
      case 2:
        return myJUnsignedIntegerType__BehaviorDescriptor;
      case 3:
        return myTestBlock__BehaviorDescriptor;
      case 4:
        return myJEqualsExpression__BehaviorDescriptor;
      case 5:
        return myXjsnarkType__BehaviorDescriptor;
      case 6:
        return myJIntegerConstant__BehaviorDescriptor;
      case 7:
        return myProgramDefinition__BehaviorDescriptor;
      case 8:
        return myJAndExpression__BehaviorDescriptor;
      case 9:
        return myJOrExpression__BehaviorDescriptor;
      case 10:
        return myValueOp__BehaviorDescriptor;
      case 11:
        return myFieldDefTable__BehaviorDescriptor;
      case 12:
        return myFieldRecord__BehaviorDescriptor;
      case 13:
        return myJNotEqualsExpression__BehaviorDescriptor;
      case 14:
        return myJUnsignedBigIntegerLiteral__BehaviorDescriptor;
      case 15:
        return myJUnsignedBigIntegerDecimalConstant__BehaviorDescriptor;
      case 16:
        return myJUnsignedBigIntegerHexConstant__BehaviorDescriptor;
      default:
        return null;
    }
  }
}
