package xjsnark.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.math.BigInteger;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class FieldDefTable_Behavior {
  public static String[] call_getIds_7553992366106442405(SNode __thisNode__) {
    return FieldDefTable__BehaviorDescriptor.getIds_id6zlb0z1MnE_(__thisNode__);
  }
  public static BigInteger call_getVal_7553992366106481809(SNode __thisNode__, String id) {
    return FieldDefTable__BehaviorDescriptor.getVal_id6zlb0z1Mxih(__thisNode__, id);
  }
}
