package xjsnark.behavior;

/*Generated by MPS */

import java.math.BigInteger;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class FieldRecord_Behavior {
  public static BigInteger call_getValue_7553992366106439082(SNode __thisNode__) {
    return FieldRecord__BehaviorDescriptor.getValue_id6zlb0z1MmQE(__thisNode__);
  }
}
